[package]
name = "crushtool"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
# byteorder = "*"
enum_primitive = "*"
log = "*"
nom = "*"
num = "*"
simple_logger = "*"
