[package]
name = "crushtool"
version = "0.1.0"
authors = ["Chris Holcombe <xfactor973@gmail.com>"]

[dependencies]
byteorder = "~0.5"
enum_primitive = "~0.1"
log = "~0.3"
nom = "~1.2"
num = "~0.1"
simple_logger = "~0.4"
clap = "~2.2"